title: kleinfeld.io
url: https://kleinfeld.io

# Use our own layout/includes; don't pull in a remote theme
theme: null
plugins: []

markdown: kramdown
kramdown:
  input: GFM

# Keep the build clean
exclude:
  - node_modules
  - vendor
  - README.md
  - .github
  - package.json
  - package-lock.json